frontend:
    environment: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-09-15T15:33:05Z"
    mac: ENC[AES256_GCM,data:Cs7TXLsmURtuCJtdkfnt1zc+4dJ/RpbY/EpaQ5e/je/L8dtv4Clms4fDfhYZ40cKda6QyoCGSiUxA9zkKgCy+7jhaC2Aqfmf3mBqFz4SmrRoStAVneaGUFEIT0BVIB0ORGVmppfla0qsES1bLW2/7lxHzswhYLNO8v2jfQ916B4=,iv:3s8f7KVuFfwZtA24SpTV+qC73YUdJXDKI/UV2kpA2Es=,tag:/ctNygsaqJKw/x3x4KF1rQ==,type:str]
    pgp:
        - created_at: "2022-09-14T13:42:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA1MXzg1c4SMLAQgAoRceoDDpqXEbiz6DaMX7YS7j5mcp+xVoemU9qY4ln7dT
            XtwAWiRVr7mf1ZDI77bQunbyWAU3zM/lFDsrlNUMAUGZzoOOtIGSnjCqCYB5JGiP
            ZfdjG88RAJx+WMIgWl66PW1ceru8We+KauQyG7bD5g59g3b5RadEhH3VER4cYJof
            VI0+NPpAcGciRsV3vxGGf4q1ppM3Pz0AnXcC+HB+hxWa5DeAhZlavFO2zYBCzw/o
            ypyLCoOcuEDSj9AY+EYnjyXIS72DXPA953/8QSaMSZ9JVKG5imtXslGEdj9PIQOp
            0rPqjZCxzydQaPZ68jXMg2Ci4gZT4ZPle9fRFxNGdtJeAScCUk+5L70orvNmWwgD
            3fFnMY6tMDd/qSqSRFEJ0Vm0M4MYSg5mgW9M64zGfw1bZLLjsIGMe2ZqQC/sZh1O
            Mrk3/xd4md/Ko8BQcaZ6lCi0olz6KWTzmQhXgNTx9A==
            =mNH9
            -----END PGP MESSAGE-----
          fp: 99E83B7490B1A9F51781E6055317CE0D5CE1230B
    unencrypted_suffix: _unencrypted
    version: 3.7.3
