frontend:
    environment:
        SENTRY_DSN:
            _default: ENC[AES256_GCM,data:8l6EM9q2FAxcBvixc0y/guIvStdOv9QfXQksFp6YAuYMJ/3s/jkZfpUgFs17dY2qg3Ze2mKLmUSxCy0hAFlOxBOfHcAha+qS6VI=,iv:uVScV6zYfR+4d8DdT/Gg23ZmCypGkIGESOieqkdXC9g=,tag:5E+JxKh+5wWU/GaAa/Dldg==,type:str]
        NEXT_PUBLIC_SENTRY_DSN:
            _default: ENC[AES256_GCM,data:qMheLmNm5Mzy9O/bg1tVxysXctCRW3XTZOFtVBssy4H3cBrf2XFoyZd/9w03jciep/zKghuKPOoVNK0928GUOXSJDnPqWFAW3p8=,iv:1qkaxjTY0jF0KWC1CBMrvWJnANhomZYArXbXGsAHVFw=,tag:BcN7VRrIGCERWsp+JVcwFg==,type:str]
        SENTRY_CSP_REPORT_URI:
            _default: ENC[AES256_GCM,data:LKEqPqJM2NPP/OpQN8fP5eMWNq4S67LB376Kc4GNOn2efu+thTBkFcdraYkLbk7AiHQG/0lEmFqlXtxv2YGNkKzs9p3RaM5XNrxEWYKp6ht61VOVeHMFSEaDs9+LAzujAJq8,iv:dVB3Rcsms9XNTbxim8WGRj3wU8mNvmyKnfZGv4LC9Ro=,tag:DrAXnd7c9Rma+ZIlJrRizg==,type:str]
        SENTRY_AUTH_TOKEN:
            _default: ENC[AES256_GCM,data:4TvbGnf7DPf6LMNZZWV0WniIrH4l916cmIkyYZwMafK2p9bGC0PdNAPcJw/yVYAR976N8R9l6Ujk7Ht5Hiqg8A==,iv:vNGmpgIpsIUpazxxYfQvoh4Eh/VW7no48hdP3624VQs=,tag:dD93MaJ0gVOeR5oSKMco5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-09-14T15:36:11Z"
    mac: ENC[AES256_GCM,data:M6tz5ochKg2joEslcMFiG34tg/ezwDxzZqlNzTFwJ7XdrnUKM9T/pb8xD6vyoaYX5y8YUpLB9ezGGTX/nbssc3VTG/rvbBcHJXWFSOBSkMzHhghy3ZmGVoKCOnWH35A20DGlyjKnxiOudMlpCGY8HsF0Uu+O6/RZta66HDjGipQ=,iv:IX+aLo0l4K9nNxRdXgEc8mKKv7ZKQkzFFaMWuppbdbM=,tag:E75w3svmLSZf8Xag/pcdaw==,type:str]
    pgp:
        - created_at: "2022-09-14T13:42:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA1MXzg1c4SMLAQgAoRceoDDpqXEbiz6DaMX7YS7j5mcp+xVoemU9qY4ln7dT
            XtwAWiRVr7mf1ZDI77bQunbyWAU3zM/lFDsrlNUMAUGZzoOOtIGSnjCqCYB5JGiP
            ZfdjG88RAJx+WMIgWl66PW1ceru8We+KauQyG7bD5g59g3b5RadEhH3VER4cYJof
            VI0+NPpAcGciRsV3vxGGf4q1ppM3Pz0AnXcC+HB+hxWa5DeAhZlavFO2zYBCzw/o
            ypyLCoOcuEDSj9AY+EYnjyXIS72DXPA953/8QSaMSZ9JVKG5imtXslGEdj9PIQOp
            0rPqjZCxzydQaPZ68jXMg2Ci4gZT4ZPle9fRFxNGdtJeAScCUk+5L70orvNmWwgD
            3fFnMY6tMDd/qSqSRFEJ0Vm0M4MYSg5mgW9M64zGfw1bZLLjsIGMe2ZqQC/sZh1O
            Mrk3/xd4md/Ko8BQcaZ6lCi0olz6KWTzmQhXgNTx9A==
            =mNH9
            -----END PGP MESSAGE-----
          fp: 99E83B7490B1A9F51781E6055317CE0D5CE1230B
    unencrypted_suffix: _unencrypted
    version: 3.7.3
