name: Checks
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code_quality:
    name: Code quality
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'WIP')"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true

      - name: Run ESLint
        run: yarn lint:eslint

      - name: Compile TypeScript
        run: yarn lint:tsc

  jest_tests:
    name: Run unit tests with Jest
    needs: [ code_quality ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true

      - name: Run Jest
        run: yarn test:jest

  pw_tests:
    name: Run components visual tests with PlayWright
    needs: [ code_quality ]
    # if: ${{ false }}
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.32.0-focal

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Install git-lfs
        run: apt-get update && apt-get install git-lfs

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true

      - name: Run PlayWright
        run: HOME=/root yarn test:pw

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 10