name: Cleanup environments

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    needs: push_to_registry
    uses: blockscout/blockscout-ci-cd/.github/workflows/cleanup.yaml@master
    with:
      appNamespace: frontend-$GITHUB_REF_NAME
    secrets: inherit
