name: Cleanup environments

on:
  pull_request:
    types:
      - closed
      - merged

jobs:
  uses: blockscout/blockscout-ci-cd/.github/workflows/cleanup.yaml@master
  with:
    appNamespace: review-front-$GITHUB_HEAD_REF_SLUG
  secrets: inherit
