name: Run E2E tests k8s

on:
  # push:
  # pull_request:
  workflow_dispatch

env:
  K8S_LOCAL_PORT: ${{ secrets.K8S_LOCAL_PORT }}
  K8S_HOST: ${{ secrets.K8S_HOST }}
  BASTION_HOST: ${{ secrets.BASTION_HOST }}
  K8S_PORT: ${{ secrets.K8S_PORT }}
  USERNAME: ${{ secrets.USERNAME }}
  BASTION_SSH_KEY: ${{secrets.BASTION_SSH_KEY}}

jobs:
  push_to_registry:
    name: Push Docker image to registry
    runs-on: ubuntu-latest
    outputs:
      shortSha: ${{ steps.output-step.outputs.short-sha }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Will automatically make nice tags, see the table here https://github.com/docker/metadata-action#basic
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/blockscout/frontend

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Add outputs
        run: |
          echo "::set-output name=short-sha::${{ env.SHORT_SHA }}"
        id: output-step

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/blockscout/frontend:prerelease-${{ env.SHORT_SHA }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_COMMIT_SHA=${{ env.SHORT_SHA }}

  deploy_and_tests:
    needs: push_to_registry
    uses: blockscout/blockscout-ci-cd/.github/workflows/e2e_new.yaml@master
    with:
      env_vars: VALUES_DIR=deploy/values/e2e,APP_NAME=e2e-front
      appNamespace: e2e-front-$GITHUB_SHA_SHORT
      frontendImage: ghcr.io/blockscout/frontend:prerelease-${{ needs.push_to_registry.outputs.shortSha }}
      blockscoutIngressHost: e2e-blockscout-$GITHUB_SHA_SHORT
      frontendIngressHost: e2e-blockscout-$GITHUB_SHA_SHORT
      gethIngressHost: e2e-geth-$GITHUB_SHA_SHORT
      scVerifierIngressHost: e2e-sc-verifier-$GITHUB_SHA_SHORT
    secrets: inherit
