name: Run code checks
on: [pull_request]
jobs:
  Check code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn
    - name: Run ESLint
      run: yarn lint:eslint
    - name: Compile TypeScript
      run: yarn lint:tsc