name: Move new issues into Triage

on:
  issues:
    types:
        - labeled

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'triage'
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Front-end tasks
          column: Triage
          repo-token: ${{ secrets.GITHUB_TOKEN }}