name: playwright
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.26.0-focal

    steps:
      - run: apt-get update && apt-get install git-lfs
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: yarn
      - name: Run your tests
        run: HOME=/root yarn test-ct
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report