name: Release

on:
    # TODO @tom2drum: remove PR trigger
    # pull_request:
    release:
        types: [ released, prereleased ]

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    label_released_issues:
        name: Label released issues
        uses: './.github/workflows/label-released-issues.yml'
        secrets: inherit
        # TODO @tom2drum: uncomment condition
        # if: ${{ github.event.action == 'released' }}
    update_project_cards:
        name: Update project tasks statuses
        needs: label_released_issues
        uses: './.github/workflows/update-project-cards.yml'
        with:
            project_name: Front-end tasks
            field_name: Status
            field_value: Released
            issues: ${{ needs.label_released_issues.outputs.issues }}
        secrets: inherit

